In [1]:
#PLEASE KNOW that this monte carlo script does not account for the content of the surrounding spaces
#if the center molecule is a phenol and it is surrounded by only spces or coal, then there is still a possibility for
#the model to say that a phenol-phenol bond occured. I'm just using this as a starting point.

#okie dokie, let's import our packages
%matplotlib inline
import numpy as np
from matplotlib import pyplot as plt

import random
from random import randrange

#I think I might steal Jason's initial random matrix code

from rescure import initial_random_matrix

#So what are our events? P-P bond, P-C bond, Nothing happens ... There's more but let's just start with that and see where we get
#I'm going to put arbitrary rates in for now
k1= 0.9
k2= 0.7
k3= 0.5

RatePhenPhen = k1 - (k2*0.2) - (k3*0.1)

RatePhenCoal = k2 - (k1*0.3) - (k3*0.2)

RateNoRxn = k3 - (k2*0.2) - (k1*0.3)

bondsum = sum([RatePhenPhen, RatePhenCoal])
ratesum = sum([bondsum, RateNoRxn])

print(RatePhenPhen)
print(RatePhenCoal)
print(RateNoRxn)
print(bondsum)
print(ratesum)

ModuleNotFoundError: No module named 'rescure'

In [ ]:
#Yeah so it looks like we need some initial states and actual objects, yeah?
t = 0

ratio = (1, 2, 1)

inital_state = initial_random_matrix(3, ratio)

print(inital_state)

[[1. 2. 1.]
 [1. 0. 1.]
 [2. 1. 0.]]


In [ ]:
#coolcoolcool now let's get our selector
event_selector = np.random.rand()
print(event_selector)

0.3881806801421902


In [ ]:
chosen_event = ratesum * event_selector
print(chosen_event)

0.4386441685606749


In [ ]:
#First, we should assign variables to each position in the matrix I think

NW = inital_state[0,0]
N = inital_state[0,1]
NE = inital_state[0,2]
W = inital_state[1,0]
CenterMol0 = inital_state[1,1]
E = inital_state[1,2]
SW = inital_state[2,0]
S = inital_state[2,1]
SE = inital_state[2,2]

print(NW)
print(N)
print(NE)
print(W)
print(CenterMol0)
print(E)
print(SW)
print(S)
print(SE)


1.0
2.0
1.0
1.0
0.0
1.0
2.0
1.0
0.0


In [ ]:
if CenterMol0 == 0.0:
    CenterMol = CenterMol0
    print('No Reaction')

if CenterMol0 == 1.0:
    if 0.0<=chosen_event<=RatePhenPhen:
        CenterMol = CenterMol0 + 2
        print ('Phenol-Phenol Bond')
    if RatePhenPhen<chosen_event<=bondsum:
        CenterMol = CenterMol0 + 3
        print('Phenol-Coal Bond')
    if bondsum<chosen_event<=ratesum:
        CenterMol = CenterMol0
        print('No Reaction')

if CenterMol0 == 2.0:
    if 0.0<=chosen_event<=RatePhenPhen:
        CenterMol = CenterMol0
        print('No Reaction')
    if RatePhenPhen<chosen_event<=bondsum:
        CenterMol = CenterMol0 + 3
        print('Phenol-Coal Bond')
    if bondsum<chosen_event<=ratesum:
        CenterMol = CenterMol0
        print('No Reaction')


No Reaction
