In [7]:
from rescure import initial_random_matrix
import numpy as np

In [8]:
ratio = (1, 2, 1)

initial_state = initial_random_matrix(15, ratio)

print(initial_state)

[[0. 0. 0. 0. 1. 0. 0. 2. 2. 1. 2. 1. 0. 0. 2.]
 [1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1.]
 [0. 1. 2. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 2. 2. 1. 1. 2.]
 [1. 2. 1. 2. 1. 1. 0. 1. 2. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 2. 1. 1. 0. 1. 2. 1. 0. 0. 2. 1.]
 [1. 2. 1. 0. 2. 2. 1. 2. 1. 1. 1. 0. 1. 2. 1.]
 [1. 1. 2. 0. 0. 0. 1. 0. 2. 1. 0. 2. 0. 1. 2.]
 [1. 1. 2. 2. 1. 1. 1. 1. 2. 2. 2. 1. 2. 1. 1.]
 [1. 1. 0. 0. 0. 2. 0. 0. 1. 0. 2. 0. 0. 1. 1.]
 [2. 2. 1. 1. 2. 1. 2. 1. 1. 1. 2. 0. 2. 1. 0.]
 [1. 0. 0. 0. 1. 1. 0. 2. 2. 1. 1. 2. 1. 1. 0.]
 [1. 2. 1. 1. 1. 0. 0. 0. 2. 1. 2. 1. 1. 1. 0.]
 [1. 2. 2. 2. 1. 1. 0. 2. 0. 1. 0. 0. 1. 1. 1.]
 [1. 2. 1. 2. 1. 1. 1. 2. 1. 0. 1. 1. 0. 2. 0.]]


In [9]:
# Test to see if the distrubution is the correct ratio:

n = len(initial_state)

voids = []
phenols = []
coals = []

for i in range(n):
    for j in range(n):
        if initial_state[i][j] == 0:
            voids.append((i, j))
        elif initial_state[i][j] == 1:
            phenols.append((i, j))
        elif initial_state[i][j] == 2:
            coals.append((i, j))

print(len(voids))
print(len(phenols))
print(len(coals))

# Looks like it's working!

54
118
53


Let's test the kernel / filter:

In [15]:
start_mol = (-2, -2)
i, j = start_mol

periphery = []

for k in range(i-1, j+2):
    for l in range(j-1, j+2):
        periphery.append(initial_state[k, l])

# Reshape the periphery array to be a 3x3 array:

periphery = np.array(periphery).reshape(3, 3)
print(periphery)

[[1. 1. 0.]
 [1. 1. 1.]
 [0. 2. 0.]]
True
True
False
True
True
True
False
True
False
