In [11]:
from rescure import initial_random_matrix
from rescure import get_rates_simplified
import numpy as np

In [12]:
ratio = (1, 2, 1)

initial_state = initial_random_matrix(15, ratio)

print(initial_state)

[[0. 2. 2. 1. 0. 1. 0. 1. 0. 1. 2. 0. 1. 1. 1.]
 [0. 1. 1. 1. 2. 0. 0. 2. 2. 2. 2. 0. 0. 1. 2.]
 [1. 1. 0. 1. 1. 2. 0. 1. 1. 0. 0. 1. 2. 1. 1.]
 [2. 1. 1. 2. 1. 1. 0. 1. 2. 1. 1. 2. 1. 1. 1.]
 [0. 0. 1. 0. 2. 1. 2. 2. 0. 0. 0. 1. 2. 1. 1.]
 [2. 0. 0. 0. 1. 0. 1. 1. 2. 0. 0. 1. 2. 1. 1.]
 [2. 0. 0. 2. 2. 2. 1. 1. 2. 1. 0. 2. 1. 1. 0.]
 [0. 2. 1. 2. 1. 1. 1. 2. 1. 1. 0. 0. 1. 0. 1.]
 [2. 1. 1. 1. 1. 2. 2. 0. 2. 1. 0. 0. 2. 1. 1.]
 [2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 2. 1. 1. 1. 1. 1. 1. 1. 0. 2. 1. 2. 0. 2.]
 [1. 2. 1. 0. 1. 1. 2. 1. 1. 1. 1. 1. 0. 2. 1.]
 [0. 1. 1. 1. 1. 1. 1. 0. 0. 2. 1. 1. 2. 1. 0.]
 [1. 0. 1. 0. 0. 1. 1. 2. 2. 2. 1. 1. 0. 2. 0.]
 [1. 1. 1. 0. 1. 1. 2. 1. 0. 1. 2. 0. 2. 1. 0.]]


In [13]:
# Test to see if the distrubution is the correct ratio:

n = len(initial_state)

voids = []
phenols = []
coals = []

for i in range(n):
    for j in range(n):
        if initial_state[i][j] == 0:
            voids.append((i, j))
        elif initial_state[i][j] == 1:
            phenols.append((i, j))
        elif initial_state[i][j] == 2:
            coals.append((i, j))

print(len(voids))
print(len(phenols))
print(len(coals))

# Looks like it's working!

56
115
54


Let's test the kernel / filter:

In [15]:
start_mol = (5, 4)
i, j = start_mol

periphery = []

for k in range(i-1, j+2):
    for l in range(j-1, j+2):
        periphery.append(initial_state[k, l]) #NOT WORKING

# Reshape the periphery array to be a 3x3 array:

# periphery = np.array(periphery).reshape(3, 3)
print(periphery)

[0.0, 2.0, 1.0, 0.0, 1.0, 0.0]


In [ ]:
# Different method of setting up the kernel / mask:

start_mol = (5, 4)
i, j = start_mol

kernel = np.zeros((3, 3))

kernel[0, 0] = 1 # Still need to figure out how to do this automatically

Testing a simple rate function calculator:

In [ ]:
# Let's say that the position of the molecule
# we are looking at is (5, 4) in the initial state
# matrix:

pos = (5, 4)

rate_matrix = get_rates_simplified(initial_state, pos)
print(rate_matrix)

[[0, 0, 0], [0, 0, 0], [0, 0, 1]]
